// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var authPostApiSessionsCmd = &cobra.Command{
	Use:   "post-api-sessions",
	Short: "Create a session (login)",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/sessions"

		params := make(map[string]string)

		headers := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, headers, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	authPostApiSessionsCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
}
