// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var automationGetApiFramesFrameIdAutoCreationIntentsIntentIdCmd = &cobra.Command{
	Use:   "get-api-frames-frame-id-auto-creation-intents-intent-id",
	Short: "Get an auto-creation intent by id",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/auto_creation_intents/{intentId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		intentIdVal, _ := cmd.Flags().GetString("intent-id")
		if intentIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "intent-id")
		}
		path = strings.Replace(path, "{intentId}", intentIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	automationGetApiFramesFrameIdAutoCreationIntentsIntentIdCmd.Flags().String("frame-id", "", "")
	_ = automationGetApiFramesFrameIdAutoCreationIntentsIntentIdCmd.MarkFlagRequired("frame-id")
	automationGetApiFramesFrameIdAutoCreationIntentsIntentIdCmd.Flags().String("intent-id", "", "")
	_ = automationGetApiFramesFrameIdAutoCreationIntentsIntentIdCmd.MarkFlagRequired("intent-id")
}
