// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var calendarsDeleteEventCmd = &cobra.Command{
	Use:   "delete-event",
	Short: "Delete a calendar event",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/calendar_events/{eventId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		eventIdVal, _ := cmd.Flags().GetString("event-id")
		if eventIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "event-id")
		}
		path = strings.Replace(path, "{eventId}", eventIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("apply-to"); v != "" {
			params["apply_to"] = v
		}

		headers := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	calendarsDeleteEventCmd.Flags().String("frame-id", "", "")
	_ = calendarsDeleteEventCmd.MarkFlagRequired("frame-id")
	calendarsDeleteEventCmd.Flags().String("event-id", "", "")
	_ = calendarsDeleteEventCmd.MarkFlagRequired("event-id")
	calendarsDeleteEventCmd.Flags().String("apply-to", "", "")
}
