// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd = &cobra.Command{
	Use:   "put-api-frames-frame-id-calendar-events-event-id",
	Short: "Update a calendar event",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/calendar_events/{eventId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		eventIdVal, _ := cmd.Flags().GetString("event-id")
		if eventIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "event-id")
		}
		path = strings.Replace(path, "{eventId}", eventIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("apply-to"); v != "" {
			params["apply_to"] = v
		}

		headers := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "data.type", JSONPath: "data.type", Type: "string"},
			{FlagName: "data.attributes", JSONPath: "data.attributes", Type: "object"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, headers, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.Flags().String("frame-id", "", "")
	_ = calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.MarkFlagRequired("frame-id")
	calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.Flags().String("event-id", "", "")
	_ = calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.MarkFlagRequired("event-id")
	calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.Flags().String("apply-to", "", "")
	calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.Flags().String("data.type", "", "")
	_ = calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.RegisterFlagCompletionFunc("data.type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"calendar_event"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.MarkFlagRequired("data.type")
	calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.Flags().String("data.attributes", "", "")
	_ = calendarsPutApiFramesFrameIdCalendarEventsEventIdCmd.MarkFlagRequired("data.attributes")
}
