// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var calendarsSetDefaultSourceCmd = &cobra.Command{
	Use:   "set-default-source",
	Short: "Set the default source calendar for new events",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/source_calendars/set_default_for_new_events"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "id", JSONPath: "id", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("POST", path, params, headers, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	calendarsSetDefaultSourceCmd.Flags().String("frame-id", "", "")
	_ = calendarsSetDefaultSourceCmd.MarkFlagRequired("frame-id")
	calendarsSetDefaultSourceCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	calendarsSetDefaultSourceCmd.Flags().String("id", "", "Source calendar id to set as default.")
	_ = calendarsSetDefaultSourceCmd.MarkFlagRequired("id")
}
