// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var calendarsGetApiFramesFrameIdCalendarEventsCmd = &cobra.Command{
	Use:   "get-api-frames-frame-id-calendar-events",
	Short: "List calendar events for a date range",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/calendar_events"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("date-min"); v != "" {
			params["date_min"] = v
		}
		if v, _ := cmd.Flags().GetString("date-max"); v != "" {
			params["date_max"] = v
		}
		if v, _ := cmd.Flags().GetString("timezone"); v != "" {
			params["timezone"] = v
		}
		if v, _ := cmd.Flags().GetString("include"); v != "" {
			params["include"] = v
		}

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	calendarsGetApiFramesFrameIdCalendarEventsCmd.Flags().String("frame-id", "", "")
	_ = calendarsGetApiFramesFrameIdCalendarEventsCmd.MarkFlagRequired("frame-id")
	calendarsGetApiFramesFrameIdCalendarEventsCmd.Flags().String("date-min", "", "")
	_ = calendarsGetApiFramesFrameIdCalendarEventsCmd.MarkFlagRequired("date-min")
	calendarsGetApiFramesFrameIdCalendarEventsCmd.Flags().String("date-max", "", "")
	_ = calendarsGetApiFramesFrameIdCalendarEventsCmd.MarkFlagRequired("date-max")
	calendarsGetApiFramesFrameIdCalendarEventsCmd.Flags().String("timezone", "", "")
	calendarsGetApiFramesFrameIdCalendarEventsCmd.Flags().String("include", "", "")
}
