// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var categoriesGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get category by id",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/categories/{categoryId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		categoryIdVal, _ := cmd.Flags().GetString("category-id")
		if categoryIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "category-id")
		}
		path = strings.Replace(path, "{categoryId}", categoryIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	categoriesGetCmd.Flags().String("frame-id", "", "")
	_ = categoriesGetCmd.MarkFlagRequired("frame-id")
	categoriesGetCmd.Flags().String("category-id", "", "")
	_ = categoriesGetCmd.MarkFlagRequired("category-id")
}
