// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var categoriesUpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "Update a category",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/categories/{categoryId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		categoryIdVal, _ := cmd.Flags().GetString("category-id")
		if categoryIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "category-id")
		}
		path = strings.Replace(path, "{categoryId}", categoryIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "data.type", JSONPath: "data.type", Type: "string"},
			{FlagName: "data.attributes", JSONPath: "data.attributes", Type: "object"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, headers, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	categoriesUpdateCmd.Flags().String("frame-id", "", "")
	_ = categoriesUpdateCmd.MarkFlagRequired("frame-id")
	categoriesUpdateCmd.Flags().String("category-id", "", "")
	_ = categoriesUpdateCmd.MarkFlagRequired("category-id")
	categoriesUpdateCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	categoriesUpdateCmd.Flags().String("data.type", "", "")
	_ = categoriesUpdateCmd.RegisterFlagCompletionFunc("data.type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"category"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = categoriesUpdateCmd.MarkFlagRequired("data.type")
	categoriesUpdateCmd.Flags().String("data.attributes", "", "")
	_ = categoriesUpdateCmd.MarkFlagRequired("data.attributes")
}
