// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var choresDeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "Delete a chore",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/chores/{choreId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		choreIdVal, _ := cmd.Flags().GetString("chore-id")
		if choreIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "chore-id")
		}
		path = strings.Replace(path, "{choreId}", choreIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("apply-to"); v != "" {
			params["apply_to"] = v
		}

		headers := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	choresDeleteCmd.Flags().String("frame-id", "", "")
	_ = choresDeleteCmd.MarkFlagRequired("frame-id")
	choresDeleteCmd.Flags().String("chore-id", "", "Chore ID or YYYY-MM-DD date (for date-based deletion of recurring chores).")
	_ = choresDeleteCmd.MarkFlagRequired("chore-id")
	choresDeleteCmd.Flags().String("apply-to", "", "")
}
