// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var choresPutApiFramesFrameIdChoresChoreIdCmd = &cobra.Command{
	Use:   "put-api-frames-frame-id-chores-chore-id",
	Short: "Update a chore",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/chores/{choreId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		choreIdVal, _ := cmd.Flags().GetString("chore-id")
		if choreIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "chore-id")
		}
		path = strings.Replace(path, "{choreId}", choreIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("apply-to"); v != "" {
			params["apply_to"] = v
		}

		headers := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "data.type", JSONPath: "data.type", Type: "string"},
			{FlagName: "data.attributes", JSONPath: "data.attributes", Type: "object"},
			{FlagName: "data.relationships", JSONPath: "data.relationships", Type: "object"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, headers, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	choresPutApiFramesFrameIdChoresChoreIdCmd.Flags().String("frame-id", "", "")
	_ = choresPutApiFramesFrameIdChoresChoreIdCmd.MarkFlagRequired("frame-id")
	choresPutApiFramesFrameIdChoresChoreIdCmd.Flags().String("chore-id", "", "")
	_ = choresPutApiFramesFrameIdChoresChoreIdCmd.MarkFlagRequired("chore-id")
	choresPutApiFramesFrameIdChoresChoreIdCmd.Flags().String("apply-to", "", "")
	choresPutApiFramesFrameIdChoresChoreIdCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	choresPutApiFramesFrameIdChoresChoreIdCmd.Flags().String("data.type", "", "")
	_ = choresPutApiFramesFrameIdChoresChoreIdCmd.RegisterFlagCompletionFunc("data.type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"chore"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = choresPutApiFramesFrameIdChoresChoreIdCmd.MarkFlagRequired("data.type")
	choresPutApiFramesFrameIdChoresChoreIdCmd.Flags().String("data.attributes", "", "")
	_ = choresPutApiFramesFrameIdChoresChoreIdCmd.MarkFlagRequired("data.attributes")
	choresPutApiFramesFrameIdChoresChoreIdCmd.Flags().String("data.relationships", "", "")
}
