// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var choresGetApiFramesFrameIdCmd = &cobra.Command{
	Use:   "get-api-frames-frame-id",
	Short: "List chores for a frame in a date range",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/chores"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("after"); v != "" {
			params["after"] = v
		}
		if v, _ := cmd.Flags().GetString("before"); v != "" {
			params["before"] = v
		}
		if v, _ := cmd.Flags().GetString("include-late"); v != "" {
			params["include_late"] = v
		}
		if v, _ := cmd.Flags().GetString("filter"); v != "" {
			params["filter"] = v
		}
		if v, _ := cmd.Flags().GetString("include-up-for-grabs"); v != "" {
			params["include_up_for_grabs"] = v
		}

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	choresGetApiFramesFrameIdCmd.Flags().String("frame-id", "", "")
	_ = choresGetApiFramesFrameIdCmd.MarkFlagRequired("frame-id")
	choresGetApiFramesFrameIdCmd.Flags().String("after", "", "")
	choresGetApiFramesFrameIdCmd.Flags().String("before", "", "")
	choresGetApiFramesFrameIdCmd.Flags().String("include-late", "", "")
	choresGetApiFramesFrameIdCmd.Flags().String("filter", "", "")
	_ = choresGetApiFramesFrameIdCmd.RegisterFlagCompletionFunc("filter", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"linked_to_profile"}, cobra.ShellCompDirectiveNoFileComp
	})
	choresGetApiFramesFrameIdCmd.Flags().String("include-up-for-grabs", "", "")
}
