// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var devicesGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get a device by id",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/devices/{deviceId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		deviceIdVal, _ := cmd.Flags().GetString("device-id")
		if deviceIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "device-id")
		}
		path = strings.Replace(path, "{deviceId}", deviceIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	devicesGetCmd.Flags().String("frame-id", "", "")
	_ = devicesGetCmd.MarkFlagRequired("frame-id")
	devicesGetCmd.Flags().String("device-id", "", "")
	_ = devicesGetCmd.MarkFlagRequired("device-id")
}
