// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var listsUpdateItemCmd = &cobra.Command{
	Use:   "update-item",
	Short: "Update a list item",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/lists/{listId}/list_items/{itemId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		listIdVal, _ := cmd.Flags().GetString("list-id")
		if listIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "list-id")
		}
		path = strings.Replace(path, "{listId}", listIdVal, 1)
		itemIdVal, _ := cmd.Flags().GetString("item-id")
		if itemIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "item-id")
		}
		path = strings.Replace(path, "{itemId}", itemIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "data.type", JSONPath: "data.type", Type: "string"},
			{FlagName: "data.attributes", JSONPath: "data.attributes", Type: "object"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, headers, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	listsUpdateItemCmd.Flags().String("frame-id", "", "")
	_ = listsUpdateItemCmd.MarkFlagRequired("frame-id")
	listsUpdateItemCmd.Flags().String("list-id", "", "")
	_ = listsUpdateItemCmd.MarkFlagRequired("list-id")
	listsUpdateItemCmd.Flags().String("item-id", "", "")
	_ = listsUpdateItemCmd.MarkFlagRequired("item-id")
	listsUpdateItemCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	listsUpdateItemCmd.Flags().String("data.type", "", "")
	_ = listsUpdateItemCmd.RegisterFlagCompletionFunc("data.type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"list_item"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = listsUpdateItemCmd.MarkFlagRequired("data.type")
	listsUpdateItemCmd.Flags().String("data.attributes", "", "")
	_ = listsUpdateItemCmd.MarkFlagRequired("data.attributes")
}
