// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var listsBulkUpdateSectionCmd = &cobra.Command{
	Use:   "bulk-update-section",
	Short: "Bulk move list items to a section",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/lists/{listId}/list_items/bulk_update_section"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		listIdVal, _ := cmd.Flags().GetString("list-id")
		if listIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "list-id")
		}
		path = strings.Replace(path, "{listId}", listIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "data.item-ids", JSONPath: "data.item_ids", Type: "array"},
			{FlagName: "data.section", JSONPath: "data.section", Type: "string"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, headers, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	listsBulkUpdateSectionCmd.Flags().String("frame-id", "", "")
	_ = listsBulkUpdateSectionCmd.MarkFlagRequired("frame-id")
	listsBulkUpdateSectionCmd.Flags().String("list-id", "", "")
	_ = listsBulkUpdateSectionCmd.MarkFlagRequired("list-id")
	listsBulkUpdateSectionCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	listsBulkUpdateSectionCmd.Flags().String("data.item-ids", "", "")
	listsBulkUpdateSectionCmd.Flags().String("data.section", "", "")
}
