// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var listsDeleteApiFramesFrameIdListsListIdCmd = &cobra.Command{
	Use:   "delete-api-frames-frame-id-lists-list-id",
	Short: "Delete a list",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/lists/{listId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		listIdVal, _ := cmd.Flags().GetString("list-id")
		if listIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "list-id")
		}
		path = strings.Replace(path, "{listId}", listIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("DELETE", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	listsDeleteApiFramesFrameIdListsListIdCmd.Flags().String("frame-id", "", "")
	_ = listsDeleteApiFramesFrameIdListsListIdCmd.MarkFlagRequired("frame-id")
	listsDeleteApiFramesFrameIdListsListIdCmd.Flags().String("list-id", "", "")
	_ = listsDeleteApiFramesFrameIdListsListIdCmd.MarkFlagRequired("list-id")
}
