// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var listsPutApiFramesFrameIdListsListIdCmd = &cobra.Command{
	Use:   "put-api-frames-frame-id-lists-list-id",
	Short: "Update a list",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/lists/{listId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		listIdVal, _ := cmd.Flags().GetString("list-id")
		if listIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "list-id")
		}
		path = strings.Replace(path, "{listId}", listIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "data.type", JSONPath: "data.type", Type: "string"},
			{FlagName: "data.attributes", JSONPath: "data.attributes", Type: "object"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PUT", path, params, headers, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	listsPutApiFramesFrameIdListsListIdCmd.Flags().String("frame-id", "", "")
	_ = listsPutApiFramesFrameIdListsListIdCmd.MarkFlagRequired("frame-id")
	listsPutApiFramesFrameIdListsListIdCmd.Flags().String("list-id", "", "")
	_ = listsPutApiFramesFrameIdListsListIdCmd.MarkFlagRequired("list-id")
	listsPutApiFramesFrameIdListsListIdCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	listsPutApiFramesFrameIdListsListIdCmd.Flags().String("data.type", "", "")
	_ = listsPutApiFramesFrameIdListsListIdCmd.RegisterFlagCompletionFunc("data.type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"list"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = listsPutApiFramesFrameIdListsListIdCmd.MarkFlagRequired("data.type")
	listsPutApiFramesFrameIdListsListIdCmd.Flags().String("data.attributes", "", "")
	_ = listsPutApiFramesFrameIdListsListIdCmd.MarkFlagRequired("data.attributes")
}
