// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var mealsAddRecipeToGroceryListCmd = &cobra.Command{
	Use:   "add-recipe-to-grocery-list",
	Short: "Add a recipe's ingredients to the grocery list",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/meals/recipes/{recipeId}/add_to_grocery_list"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		recipeIdVal, _ := cmd.Flags().GetString("recipe-id")
		if recipeIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "recipe-id")
		}
		path = strings.Replace(path, "{recipeId}", recipeIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("POST", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	mealsAddRecipeToGroceryListCmd.Flags().String("frame-id", "", "")
	_ = mealsAddRecipeToGroceryListCmd.MarkFlagRequired("frame-id")
	mealsAddRecipeToGroceryListCmd.Flags().String("recipe-id", "", "")
	_ = mealsAddRecipeToGroceryListCmd.MarkFlagRequired("recipe-id")
}
