// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var mealsGetApiFramesFrameIdMealsSittingsSittingIdInstancesCmd = &cobra.Command{
	Use:   "get-api-frames-frame-id-meals-sittings-sitting-id-instances",
	Short: "List instances of a recurring meal sitting",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/meals/sittings/{sittingId}/instances"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		sittingIdVal, _ := cmd.Flags().GetString("sitting-id")
		if sittingIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "sitting-id")
		}
		path = strings.Replace(path, "{sittingId}", sittingIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	mealsGetApiFramesFrameIdMealsSittingsSittingIdInstancesCmd.Flags().String("frame-id", "", "")
	_ = mealsGetApiFramesFrameIdMealsSittingsSittingIdInstancesCmd.MarkFlagRequired("frame-id")
	mealsGetApiFramesFrameIdMealsSittingsSittingIdInstancesCmd.Flags().String("sitting-id", "", "")
	_ = mealsGetApiFramesFrameIdMealsSittingsSittingIdInstancesCmd.MarkFlagRequired("sitting-id")
}
