// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var messagesGetApiFramesFrameIdMessagesMessageIdCmd = &cobra.Command{
	Use:   "get-api-frames-frame-id-messages-message-id",
	Short: "Get a message by id",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/messages/{messageId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		messageIdVal, _ := cmd.Flags().GetString("message-id")
		if messageIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "message-id")
		}
		path = strings.Replace(path, "{messageId}", messageIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	messagesGetApiFramesFrameIdMessagesMessageIdCmd.Flags().String("frame-id", "", "")
	_ = messagesGetApiFramesFrameIdMessagesMessageIdCmd.MarkFlagRequired("frame-id")
	messagesGetApiFramesFrameIdMessagesMessageIdCmd.Flags().String("message-id", "", "")
	_ = messagesGetApiFramesFrameIdMessagesMessageIdCmd.MarkFlagRequired("message-id")
}
