// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var rewardsPatchApiFramesFrameIdRewardsRewardIdCmd = &cobra.Command{
	Use:   "patch-api-frames-frame-id-rewards-reward-id",
	Short: "Update a reward",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/rewards/{rewardId}"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		rewardIdVal, _ := cmd.Flags().GetString("reward-id")
		if rewardIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "reward-id")
		}
		path = strings.Replace(path, "{rewardId}", rewardIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		bodyFieldDefs := []runtime.BodyFieldDef{
			{FlagName: "data.type", JSONPath: "data.type", Type: "string"},
			{FlagName: "data.attributes", JSONPath: "data.attributes", Type: "object"},
		}
		bodyBytes, err := runtime.BuildBody(cmd, bodyFieldDefs)
		if err != nil {
			return fmt.Errorf("build request body: %w", err)
		}
		resp, err := client.Do("PATCH", path, params, headers, bodyBytes)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.Flags().String("frame-id", "", "")
	_ = rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.MarkFlagRequired("frame-id")
	rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.Flags().String("reward-id", "", "")
	_ = rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.MarkFlagRequired("reward-id")
	rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.Flags().String("data", "", "Request body JSON, @file, or @- for stdin")
	rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.Flags().String("data.type", "", "")
	_ = rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.RegisterFlagCompletionFunc("data.type", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"reward"}, cobra.ShellCompDirectiveNoFileComp
	})
	_ = rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.MarkFlagRequired("data.type")
	rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.Flags().String("data.attributes", "", "")
	_ = rewardsPatchApiFramesFrameIdRewardsRewardIdCmd.MarkFlagRequired("data.attributes")
}
