// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var rewardsPostApiFramesFrameIdRewardsRewardIdUnredeemCmd = &cobra.Command{
	Use:   "post-api-frames-frame-id-rewards-reward-id-unredeem",
	Short: "Un-redeem a reward",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/rewards/{rewardId}/unredeem"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)
		rewardIdVal, _ := cmd.Flags().GetString("reward-id")
		if rewardIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "reward-id")
		}
		path = strings.Replace(path, "{rewardId}", rewardIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("POST", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	rewardsPostApiFramesFrameIdRewardsRewardIdUnredeemCmd.Flags().String("frame-id", "", "")
	_ = rewardsPostApiFramesFrameIdRewardsRewardIdUnredeemCmd.MarkFlagRequired("frame-id")
	rewardsPostApiFramesFrameIdRewardsRewardIdUnredeemCmd.Flags().String("reward-id", "", "")
	_ = rewardsPostApiFramesFrameIdRewardsRewardIdUnredeemCmd.MarkFlagRequired("reward-id")
}
