// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var rewardsListCmd = &cobra.Command{
	Use:   "list",
	Short: "List rewards",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/rewards"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)

		params := make(map[string]string)
		if v, _ := cmd.Flags().GetString("redeemed-at-min"); v != "" {
			params["redeemed_at_min"] = v
		}
		if v, _ := cmd.Flags().GetString("redeemed-at-max"); v != "" {
			params["redeemed_at_max"] = v
		}

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	rewardsListCmd.Flags().String("frame-id", "", "")
	_ = rewardsListCmd.MarkFlagRequired("frame-id")
	rewardsListCmd.Flags().String("redeemed-at-min", "", "")
	rewardsListCmd.Flags().String("redeemed-at-max", "", "")
}
