// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"fmt"
	"strings"

	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var taskBoxGetApiFramesFrameIdTaskBoxItemsCmd = &cobra.Command{
	Use:   "get-api-frames-frame-id-task-box-items",
	Short: "List task box items",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/frames/{frameId}/task_box/items"
		frameIdVal, _ := cmd.Flags().GetString("frame-id")
		if frameIdVal == "" {
			return fmt.Errorf("required flag --%s not set", "frame-id")
		}
		path = strings.Replace(path, "{frameId}", frameIdVal, 1)

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
	taskBoxGetApiFramesFrameIdTaskBoxItemsCmd.Flags().String("frame-id", "", "")
	_ = taskBoxGetApiFramesFrameIdTaskBoxItemsCmd.MarkFlagRequired("frame-id")
}
