// Code generated by onlycli; DO NOT EDIT.

package commands

import (
	"github.com/skylight/skylight-cli/runtime"
	"github.com/spf13/cobra"
)

var userGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get current user",
	RunE: func(cmd *cobra.Command, args []string) error {
		client := runtime.NewClientFromConfig(cmd)

		path := "/api/user"

		params := make(map[string]string)

		headers := make(map[string]string)
		resp, err := client.Do("GET", path, params, headers, nil)
		if err != nil {
			return err
		}

		return runtime.PrintOutput(cmd, resp)
	},
}

func init() {
}
